# Config TLS Certificate-https//
apiVersion: v1
kind: Secret
metadata:
# this must be name secret name declared in config tls file
  name: myapp-secret-tls
  namespace: default # They must have same namespace
data:
  tls.crt: base64 encoded cert
  tls.key: base64 encoded key
type: kubernetes.io/tls